<?php
// There are no orientations available
variable_set('psfc_orientation_no_orientations', 35);

// Text below list of available orientations
variable_set('psfc_orientation_upcoming_orientations', 36);

// What is an online account (login page left)
variable_set('psfc_orientation_why_account', 37);

// Account creation instructions (login page right)
variable_set('psfc_orientation_account_create', 38);

// New user signed up as part of orientation registration
variable_set('psfc_orientation_new_user_from_orientation', 86);

// New user signed up from another form
variable_set('psfc_orientation_new_user', 87);

// Confirm orientation details page
variable_set('psfc_orientation_confirm_orientation_page', 40);

// Session no longer available
variable_set('psfc_orientation_orientation_filled', 41);

//  Could not register addiontional attendees
variable_set('psfc_orientation_no_additional_attendees', 42);

// Thank you for confirming your orientation
variable_set('psfc_orientation_confirmation_thank_you', 43);

// Cancellation completion
variable_set('psfc_orientation_registrant_removed', 44);

