<?php
// There are no orientations availalbe
variable_set('psfc_orientation_no_orientations', 123);

// Text below list of available orientations
variable_set('psfc_orientation_upcoming_orientations', 123);

// What is an online account (login page left)
variable_set('psfc_orientation_why_account', 123);

// Account creation instructions (login page right)
variable_set('psfc_orientation_account_create', 123);

// Add additional attendees page
variable_set('psfc_orientation_add_additional_instructions', 123);

// Confirm orientation details page
variable_set('psfc_orientation_confirm_orientation_page', 123);

// Session no longer available
variable_set('psfc_orientation_orientation_filled', 123);

//  Could not register addiontional attendees
variable_set('psfc_orientation_no_additional_attendees', 123);

// Thank you for confirming your orientation
variable_set('psfc_orientation_confirmation_thank_you', 123);

// Cancelation completion
variable_set('psfc_orientation_registrant_removed', 123);

