<?php

function oldimport_menu(){

	$items["admin/settings/oldimport"] = array(
		"title" => "Import Old Coop Site",
		"description" => "Import old Coop navigational structure and page content",
		"page callback" => "drupal_get_form",
		"page arguments" => array("oldimport_admin_settings"),
		"access arguments" => array("administer site configuration"),
		"type" => MENU_NORMAL_ITEM,
		"file" => "oldimport.inc",
	);
	return $items;
}

?>