<?php
/**
 * Implementation of hook_block().
 */
function psfc_member_data_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op ==  'list') {
      $blocks = array();
      $blocks[0] = array(
        'info' => t('Member status block'),
        'cache' => BLOCK_CACHE_PER_PAGE
      );
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => t(''),
          'content' => psfc_member_data_block_0(),
        );
        break;
    }
    return $block;
  }
}
/**
 * Define the member status block conent
 */
function psfc_member_data_block_0() {
  global $user;
  if ($user->uid == 0) {
    return;
  }
  $orientation_status = psfc_orientation_user_orientation_status($user->uid);
  if ($orientation_status != 1) {
    $status = $orientation_status;
  }
  elseif ($orientation_status == 1) {
    // TODO: Here is where we will have to call in actual member status once
    //  we start pulling in the member data.
    $status = t('You have completed orientation.');
  }
  else {
    $status = t('Unkown status');
  }
  $output = t('You are logged in as:') .'<br />';
  $output .= '<div class="username">' . $user->name . '</div>';
  $output .= '<div>'. $status .'</div>';
  $output .= '<div>'. l('Your registration status', 'orientation/status/registered') .'</div>';
  $output .= '<div>'. l('Log Out', 'logout') .'</div>';
  return $output;
}
