<?php
/**
 * Implementation of hook_block().
 */
function psfc_member_data_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op ==  'list') {
      $blocks = array();
      $blocks[0] = array(
        'info' => t('Member status block'),
        'cache' => BLOCK_CACHE_PER_PAGE
      );
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => t(''),
          'content' => psfc_member_data_block_0(),
        );
        break;
    }
    return $block;
  }
}
/**
 * Define the member status block conent
 */
function psfc_member_data_block_0() {
  global $user;
    
  // make this bigger:
  $output = '<div id="header_user">';
  if ($user->uid == 0) {
    $output .= '<span class="login">';
    $output .= l(t('Log in or Create an Account'), 'login');
    $output .= '</span></div>';
    return $output;
  }

// JE: This is not going to be dynamic just yet.
//
//  $orientation_status = psfc_orientation_user_orientation_status($user->uid);
//  if ($orientation_status != 1) {
//    $status = $orientation_status;
//  }
//  elseif ($orientation_status == 1) {
    // TODO: Here is where we will have to call in actual member status once
    //  we start pulling in the member data.
//    $status = t('Orientation Status');
//  }
//  else {
//    $status = t('Unknown status');
//  }
   
  $status = t('Orientation Status');

  $output .= t('Hi, ');
  $output .= '<span class="username">' . $user->name . '</span>';
  $output .= '<span class="status">';
  $output .= l(t('Orientation Status'), 'join/orientation/status');
  $output .= '</span>';  
  $output .= '<span class="logout">'. l('Log Out', 'logout') .'</span>';

  $output .= '</div>';

  return $output;
}
