<?php
/**
 * Implementation of hook_block().
 */
function psfc_member_data_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op ==  'list') {
    $blocks = array();
    $blocks[0] = array(
      'info' => t('Member status block'),
      'cache' => BLOCK_CACHE_NO_CACHE,
    );
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => t(''),
          'content' => psfc_member_data_block_0(),
        );
        break;
    }
    return $block;
  }
}
/**
 * Define the member status block conent
 */
function psfc_member_data_block_0() {
  global $user;
    
  // make this bigger:
  $output = '<div id="header_user">';
  if ($user->uid == 0) {
    $output .= '<span class="login">';
    $output .= l(t('Log in or Create an Account'), 'login');
    $output .= '</span></div>';
    return $output;
  }

  /**
   *  Orientation statuses
   *  0 = User has attended a registration
   *  1 = User has select and confirmed a registration slot
   *  2 = User has selected but not confirmed
   *  3 = User has neither selected, confirmed, or completed reg
   */
  $orientation_status = psfc_orientation_user_orientation_status($user->uid);
  if ($orientation_status != 0) {
    $status_link_text = t('Orientation Status');
    $status_link = 'join/orientation/status';
  }
  else {
    // TODO: Here is where we will have to call in actual member status once
    //  we start pulling in the member data.
    $status_text = t('Member status');
    $status_link = 'user';
  }
   
  $status = t('Orientation Status');

  $output .= t('Hi, ');
  $output .= '<span class="username">' . $user->name . '</span>';
  $output .= '<span class="status">';
  $output .= l($status_link_text, $status_link);
  $output .= '</span>';  
  $output .= '<span class="logout">'. l('Log Out', 'logout') .'</span>';

  $output .= '</div>';

  return $output;
}
